variable "aws_region" {}
variable "environment" {}
variable "vpc_name" {}
variable "vpc_id" {}
variable "cidr" {}
variable "security_group_cidr" {}
variable "instance_type" {}
variable "private_subnets" {}
variable "public_subnets" {}
variable "rds_sg" {}
variable "allowed_cidr_blocks" {}
variable "aws_zones" {}
variable "private_subnet_1" {}
variable "private_subnet_2" {}
variable "private_subnet_3" {}
variable "subnet_name_private" {}
variable "db_params_group" {}
variable "db_version" {}
variable "db_password" {}
variable "db_user" {}
variable "db_storage" {}
variable "db_instance_class" {}
variable "db_name" {}
variable "aws_key" {}
variable "volume_type" {}
variable "volume_root_size" {}
variable "volume_data_size" {}
variable "instance_name" {}
variable "zone_id" {}
variable "dns_name" {}

